#!/bin/bash 
### Begin BSUB Options 
#BSUB -P CPH121
#BSUB -J bench.g30.smt2.r100
#BSUB -W 00:05
#BSUB -nnodes 5
#BSUB -alloc_flags "smt2"
### End BSUB Options and begin shell commands

export OMP_NUM_THREADS=12

cat  inputs/test_H2O.size4600.nrep100.perf | jsrun -n 30 -a 1 -c 6 -g 1 -r 6 -l CPU-CPU -d packed -b rs /gpfs/alpine/scratch/alicej/cph121/dbcsr/build/tests/dbcsr_perf
cat inputs/test_H2O.size11500.nrep100.perf | jsrun -n 30 -a 1 -c 6 -g 1 -r 6 -l CPU-CPU -d packed -b rs /gpfs/alpine/scratch/alicej/cph121/dbcsr/build/tests/dbcsr_perf
cat inputs/test_H2O.size23000.nrep100.perf | jsrun -n 30 -a 1 -c 6 -g 1 -r 6 -l CPU-CPU -d packed -b rs /gpfs/alpine/scratch/alicej/cph121/dbcsr/build/tests/dbcsr_perf
